version: '3.8'

services:
  python-app:
    image: python:3.11-slim
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["sh", "-c", "pip install --no-cache-dir -r requirements.txt && python script.py"]